In [1]:
#!conda install -c conda-forge opencv

In [2]:
import os
import numpy as np

In [3]:
import cv2
IMGSIZE = (128, 128)
CNAMES = ['buildings', 'forest', 'glacier', 'mountain', 'sea', 'street']
X_tr, y_tr, X_ts, y_ts = [], [], [], []
for label in CNAMES:
    path = "." + '/seg_train/seg_train/' + label
    for f in sorted([_ for _ in os.listdir(path) if _.lower().endswith('.jpg')]):
        X_tr += [cv2.resize(cv2.imread(os.path.join(path,f)), IMGSIZE)]
        y_tr += [CNAMES.index(label)]

In [4]:
IMGSIZE = (128, 128)
CNAMES = ['buildings', 'forest', 'glacier', 'mountain', 'sea', 'street']
for label in CNAMES:
    path = "." + '/seg_test/seg_test/' + label
    for f in sorted([_ for _ in os.listdir(path) if _.lower().endswith('.jpg')]):
        X_ts += [cv2.resize(cv2.imread(os.path.join(path,f)), IMGSIZE)]
        y_ts += [CNAMES.index(label)]

In [5]:
cv2.imshow('i',np.array(X_ts[0] ,dtype=np.uint8))
cv2.waitKey(0)
cv2.destroyWindow('i')

error: OpenCV(4.7.0) D:\a\opencv-python\opencv-python\opencv\modules\highgui\src\window_w32.cpp:1261: error: (-27:Null pointer) NULL window: 'i' in function 'cvDestroyWindow'


In [ ]:
cv2.imshow('i',np.array(X_tr[0] ,dtype=np.uint8))
cv2.waitKey(0)
cv2.destroyWindow('i')

In [ ]:
cv2.imshow('i',np.array(X_tr[1] ,dtype=np.uint8))
cv2.waitKey(0)
cv2.destroyWindow('i')

In [ ]:
cv2.imshow('i',np.array(X_tr[2] ,dtype=np.uint8))
cv2.waitKey(0)
cv2.destroyWindow('i')

In [6]:
#q1
number_of_color_channels=X_tr[0].shape[2]
number_of_color_channels

3

In [7]:
#q2
X_trnp = np.array(X_tr)
y_trnp = np.array(y_tr)
X_trnp.shape

(14034, 128, 128, 3)

In [8]:
!pip install keras


[notice] A new release of pip is available: 23.0 -> 23.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip


In [9]:
!pip install tensorflow


[notice] A new release of pip is available: 23.0 -> 23.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip


In [10]:
from keras.utils import np_utils

In [11]:
y_tr_cat = np_utils.to_categorical(y_trnp, 6)
y_tr_cat

array([[1., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0.],
       ...,
       [0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0., 1.]], dtype=float32)

In [12]:
y_tr = y_tr_cat

In [13]:
X_scaled = X_trnp/255
X_scaled

array([[[[0.96078431, 0.96862745, 0.96862745],
         [0.96078431, 0.96862745, 0.96862745],
         [0.96470588, 0.97254902, 0.97254902],
         ...,
         [0.97254902, 0.97254902, 0.97254902],
         [0.96470588, 0.96862745, 0.96862745],
         [0.96078431, 0.96862745, 0.96862745]],

        [[0.95686275, 0.96470588, 0.96470588],
         [0.96078431, 0.96862745, 0.96862745],
         [0.96078431, 0.96862745, 0.96862745],
         ...,
         [0.97254902, 0.97254902, 0.97254902],
         [0.96470588, 0.96862745, 0.96862745],
         [0.96078431, 0.96862745, 0.96862745]],

        [[0.95686275, 0.96470588, 0.96470588],
         [0.95686275, 0.96470588, 0.96470588],
         [0.96078431, 0.96862745, 0.96862745],
         ...,
         [0.97254902, 0.97254902, 0.97254902],
         [0.96470588, 0.96862745, 0.96862745],
         [0.96078431, 0.96862745, 0.96862745]],

        ...,

        [[0.18431373, 0.19215686, 0.19607843],
         [0.21568627, 0.22352941, 0.22745098]

In [14]:
X_scaled.shape

(14034, 128, 128, 3)

In [15]:
y_trnp.shape

(14034,)

In [16]:
X_trnp = X_scaled

In [17]:
X_trnp

array([[[[0.96078431, 0.96862745, 0.96862745],
         [0.96078431, 0.96862745, 0.96862745],
         [0.96470588, 0.97254902, 0.97254902],
         ...,
         [0.97254902, 0.97254902, 0.97254902],
         [0.96470588, 0.96862745, 0.96862745],
         [0.96078431, 0.96862745, 0.96862745]],

        [[0.95686275, 0.96470588, 0.96470588],
         [0.96078431, 0.96862745, 0.96862745],
         [0.96078431, 0.96862745, 0.96862745],
         ...,
         [0.97254902, 0.97254902, 0.97254902],
         [0.96470588, 0.96862745, 0.96862745],
         [0.96078431, 0.96862745, 0.96862745]],

        [[0.95686275, 0.96470588, 0.96470588],
         [0.95686275, 0.96470588, 0.96470588],
         [0.96078431, 0.96862745, 0.96862745],
         ...,
         [0.97254902, 0.97254902, 0.97254902],
         [0.96470588, 0.96862745, 0.96862745],
         [0.96078431, 0.96862745, 0.96862745]],

        ...,

        [[0.18431373, 0.19215686, 0.19607843],
         [0.21568627, 0.22352941, 0.22745098]

In [ ]:
cv2.imshow('i',np.array(X_tr[1] ,dtype=np.uint8))
cv2.waitKey(0)
cv2.destroyWindow('i')

In [18]:
import numpy as np

import torch
import torch.nn as nn
import torch.optim as optim

class CustomMLP(nn.Module):
    """ A PyTorch neural network model """
    def __init__(self, n_hidden=30, epochs=100, eta=0.05, minibatch_size=50):
        super(CustomMLP, self).__init__()
        self.n_hidden = n_hidden  # hidden layer size
        self.epochs = epochs  # number of learning iterations
        self.eta = eta  # learning rate
        self.minibatch_size = minibatch_size  # size of training batch - 1 would not work
        self.fc1, self.fc2, self.fc3,self.fc4 = None, None, None,None

    def _forward(self, X, apply_softmax=False):
        assert self.fc1 != None
        X = nn.functional.relu(self.fc1(X))
        X = nn.functional.relu(self.fc2(X))
        X = nn.functional.relu(self.fc4(X))
        X = self.fc3(X)
        if apply_softmax:
            X = nn.functional.softmax(X, dim=1)
        return X

    def _reset(self):
        for m in self.modules():
            if isinstance(m, nn.Linear):
                 m.reset_parameters()

    def predict(self, _X):
        assert self.fc1 is not None
        net_out = self._forward(_X, apply_softmax=True)
        p_values, indices = net_out.max(dim=1)
        return indices

    def fit(self, X_train, y_train):
        # Convert to tensors
        
        
        self._reset()  # Reset the neural network weights
        n_output= np.unique(y_train).shape[0]  # number of class labels
        n_features= X_train.shape[1]

        self.fc1 = nn.Linear(n_features, self.n_hidden)  # A simple input layer
        self.fc2 = nn.Linear(self.n_hidden, self.n_hidden)  # A simple hidden layer
        self.fc4 = nn.Linear(self.n_hidden, self.n_hidden)  # A simple hidden layer
        self.fc3 = nn.Linear(self.n_hidden, n_output)  # A simple output layer
        
        optimizer = optim.SGD(self.parameters(), lr=self.eta, momentum=0.9)
        loss_func = nn.CrossEntropyLoss()

        for _ in range(self.epochs):
            indices = np.arange(X_train.shape[0])
            
            for start_idx in range(0, indices.shape[0] - self.minibatch_size + 1, self.minibatch_size):
                batch_idx = indices[start_idx:start_idx + self.minibatch_size]
                optimizer.zero_grad()
                
                net_out = self._forward(X_train[batch_idx])
                
                loss = loss_func(net_out, y_train[batch_idx])
                loss.backward()
                optimizer.step()

In [47]:
class PyTorchMLP(nn.Module):  # One hidden layer
    def __init__(self, n_hidden=10,n_hidden_2=10, epochs=100, eta=0.001, minibatch_size=50, seed=0):
        super(PyTorchMLP, self).__init__()
        self.random = np.random.RandomState(seed)  # shuffle mini batches
        self.n_hidden = n_hidden  # size of the hidden layer
        self.n_hidden_2 = n_hidden_2
        self.epochs = epochs  # number of iterations
        self.eta = eta  # learning rate
        self.minibatch_size = minibatch_size  # size of training batch - 1 would not work
        self.optimizer = None
        self.loss_func = torch.nn.CrossEntropyLoss()
        self.model = None

    def init_layers(self, _M:int, _K:int) -> None:
        # data structure
        self.model = torch.nn.Sequential(
            torch.nn.Linear(_M, self.n_hidden),
            torch.nn.Sigmoid(),
            torch.nn.Linear(self.n_hidden, self.n_hidden),
            torch.nn.Sigmoid(),
            torch.nn.Linear(self.n_hidden, self.n_hidden_2),
            torch.nn.Sigmoid(),
            torch.nn.Linear(self.n_hidden_2, self.n_hidden_2),
            torch.nn.Sigmoid(),
            torch.nn.Linear(self.n_hidden_2, _K),
        )
    
    def predict(self, _X):
        _X = torch.FloatTensor(_X)
        assert self.model is not None
        self.model.eval()
        with torch.no_grad():
            y_pred = np.argmax(self.model(_X), axis=1)
        self.model.train()
        return y_pred.numpy()

    def fit(self, _X_train, _y_train, info=False):
        import sys
        _X_train, _y_train = torch.FloatTensor(_X_train), torch.LongTensor(_y_train)
        n_features= _X_train.shape[1]
        n_output= np.unique(_y_train).shape[0]  # number of class labels
        
        self.init_layers(n_features, n_output)
        self.optimizer = torch.optim.Rprop(self.model.parameters(), lr=self.eta)  # connect model to optimizer

        for i in range(self.epochs):
            indices = np.arange(_X_train.shape[0])
            self.random.shuffle(indices)  # shuffle the data each epoch

            for start_idx in range(0, indices.shape[0] - self.minibatch_size + 1, self.minibatch_size):
                batch_idx = indices[start_idx:start_idx + self.minibatch_size]
                self.optimizer.zero_grad()
                
                net_out = self.model(_X_train[batch_idx])
                
                loss = self.loss_func(net_out, _y_train[batch_idx])
                loss.backward()
                self.optimizer.step()
                
                if info:
                    sys.stderr.write(f"\r{i+1:03d} Loss: {loss.item():6.5f}")
                    sys.stderr.flush()
        return self
    
    
class MLP2(PyTorchMLP):
    def init_layers(self, _M, _K):
        self.model = torch.nn.Sequential(
            torch.nn.Linear(_M, self.n_hidden),
            torch.nn.Sigmoid(),
            torch.nn.Dropout(0.1),
            torch.nn.Linear(self.n_hidden, self.n_hidden),
            torch.nn.Sigmoid(),
            torch.nn.Dropout(0.1),
            torch.nn.Linear(self.n_hidden, self.n_hidden_2),
            torch.nn.Sigmoid(),
            torch.nn.Dropout(0.1),
            torch.nn.Linear(self.n_hidden_2, self.n_hidden_2),
            torch.nn.ReLU(),
            torch.nn.Dropout(0.1),
            torch.nn.Linear(self.n_hidden_2, _K),
        )

In [19]:
import sys

In [20]:
X_trt, y_trt = torch.tensor(X_trnp), torch.tensor(y_trnp)

In [21]:
X_tr

[array([[[245, 247, 247],
         [245, 247, 247],
         [246, 248, 248],
         ...,
         [248, 248, 248],
         [246, 247, 247],
         [245, 247, 247]],
 
        [[244, 246, 246],
         [245, 247, 247],
         [245, 247, 247],
         ...,
         [248, 248, 248],
         [246, 247, 247],
         [245, 247, 247]],
 
        [[244, 246, 246],
         [244, 246, 246],
         [245, 247, 247],
         ...,
         [248, 248, 248],
         [246, 247, 247],
         [245, 247, 247]],
 
        ...,
 
        [[ 47,  49,  50],
         [ 55,  57,  58],
         [ 65,  67,  68],
         ...,
         [ 58,  61,  66],
         [ 38,  41,  46],
         [ 60,  63,  68]],
 
        [[ 65,  66,  67],
         [ 46,  48,  49],
         [ 67,  69,  70],
         ...,
         [ 33,  36,  41],
         [ 38,  41,  47],
         [ 45,  48,  53]],
 
        [[ 57,  59,  60],
         [ 52,  54,  55],
         [ 68,  70,  71],
         ...,
         [ 29,  32,  37],
  

In [22]:
X_trf = torch.flatten(X_trt, start_dim=1)


In [23]:
X_trf=X_trf.float()
X_trf

tensor([[0.9608, 0.9686, 0.9686,  ..., 0.2039, 0.2157, 0.2353],
        [0.7294, 0.4745, 0.2745,  ..., 0.1608, 0.2196, 0.2863],
        [0.9686, 0.7608, 0.5137,  ..., 0.2235, 0.6000, 0.5059],
        ...,
        [0.2902, 0.2627, 0.2745,  ..., 0.5294, 0.5529, 0.5451],
        [0.4275, 0.1333, 0.0078,  ..., 0.0235, 0.0157, 0.0275],
        [0.4706, 0.4353, 0.3843,  ..., 0.5098, 0.5373, 0.5490]])

In [24]:
y_trt = y_trt.long()

In [25]:
%%time

clf = CustomMLP(n_hidden=50,minibatch_size=200)

clf.fit(X_trf,y_trt)



CPU times: total: 9min 30s
Wall time: 8min 21s


In [71]:
clf_bad = clf

In [48]:
%%time

clf = MLP2()

clf.fit(X_trf,y_trt)



CPU times: total: 12min 9s
Wall time: 12min 28s


MLP2(
  (loss_func): CrossEntropyLoss()
  (model): Sequential(
    (0): Linear(in_features=49152, out_features=10, bias=True)
    (1): Sigmoid()
    (2): Dropout(p=0.1, inplace=False)
    (3): Linear(in_features=10, out_features=10, bias=True)
    (4): Sigmoid()
    (5): Dropout(p=0.1, inplace=False)
    (6): Linear(in_features=10, out_features=10, bias=True)
    (7): Sigmoid()
    (8): Dropout(p=0.1, inplace=False)
    (9): Linear(in_features=10, out_features=10, bias=True)
    (10): ReLU()
    (11): Dropout(p=0.1, inplace=False)
    (12): Linear(in_features=10, out_features=6, bias=True)
  )
)

In [26]:

X_tsnp = np.array(X_ts)/255
y_tsnp = np.array(y_ts)
y_tsnp= np_utils.to_categorical(y_tsnp, 6)
X_tst, y_tst = torch.tensor(X_tsnp), torch.tensor(y_tsnp)


In [27]:
X_tst

tensor([[[[0.6824, 0.4706, 0.3686],
          [0.7294, 0.5451, 0.4471],
          [0.7686, 0.6275, 0.5412],
          ...,
          [0.8118, 0.5804, 0.4275],
          [0.8118, 0.5804, 0.4275],
          [0.8157, 0.5843, 0.4314]],

         [[0.6706, 0.4980, 0.3961],
          [0.8431, 0.6784, 0.5882],
          [0.7137, 0.5725, 0.4941],
          ...,
          [0.8039, 0.5725, 0.4118],
          [0.8039, 0.5725, 0.4157],
          [0.8078, 0.5725, 0.4157]],

         [[0.8039, 0.6980, 0.6039],
          [0.8157, 0.6941, 0.6118],
          [0.7451, 0.6118, 0.5451],
          ...,
          [0.7961, 0.5647, 0.4000],
          [0.8000, 0.5647, 0.4000],
          [0.7961, 0.5647, 0.4000]],

         ...,

         [[0.8824, 0.8157, 0.7804],
          [0.8824, 0.8157, 0.7804],
          [0.8784, 0.8118, 0.7765],
          ...,
          [0.9451, 0.8980, 0.8745],
          [0.9490, 0.9059, 0.8824],
          [0.9529, 0.9137, 0.8863]],

         [[0.8784, 0.8078, 0.7686],
          [0.8784

In [28]:
X_tsf = torch.flatten(X_tst, start_dim=1)
X_tsf=X_tsf.float()
y_tst = y_tst.long()

In [29]:
y_pred = clf_bad.predict(X_tsf)

In [49]:

y_pred2 = clf.predict(X_tsf)

In [50]:
y_pred2

array([4, 2, 4, ..., 4, 2, 1], dtype=int64)

In [45]:
y_pred

tensor([4, 4, 4,  ..., 4, 4, 4])

In [70]:
1 in list(y_pred)

False

In [60]:
def acc(actual,pred):
    #print(actual)
    #print(pred)
    total = len(pred)
    score = 0
    for i in range(len(pred)):
        if 1==tuple(actual[i])[pred[i]]:
            score+=1
    return score/total

In [74]:
from sklearn.metrics import accuracy_score

accuracy = acc(list(y_tst), list(y_pred2))

In [75]:
accuracy

0.293

Q3 failures:
I tried to change amount of layers, layer size, batch size, epochs... I also tried 1 hot encoding as opposed to ordinal encoding.  I also realized that the code from the notebook was returning answers of all 4s, so I instead copied the NN from the assignment of week 12.  For some reason, not all categories are represented in this NN's predictions, perhaps due to underrepresentation of a category, and extreme overfitting.

Q4:
Flatten the input image dimensions to 1D
Normalize the image pixel values
One-Hot Encode the target
Build a CNN with 1 hidden layer, more if necessary, but some sources say only 1 is needed
Train and test the model